name: Publish

on:
    release:
        types:
            - created

jobs:
    run-test:
        name: 'Running test'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - name: Run test
              run: |
                  npm ci
                  npm test

    deploy-storybook:
        name: 'Deploying storybook'
        needs: run-test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - name: Install and build
              run: |
                  npm install
                  npm run build
            - uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  GITHUB_TOKEN: ${{ secrets.auth_token }}
                  BRANCH: gh-pages
                  FOLDER: stories

    publish:
        name: 'Publish to github packages'
        needs: run-test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://npm.pkg.github.com/

            - name: Build
              run: |
                  npm ci
                  npm run stencil:build

            - name: Publish components
              run: |
                  npm publish

            - name: Publish react wrapper
              run: |
                  npm install
                  npm install @avrghz/brick-components@latest
                  npm run build
                  npm publish
              working-directory: ./react

              env:
                  NODE_AUTH_TOKEN: ${{secrets.auth_token}}
